### PR TITLE
Handle null values.

### PR DESCRIPTION
**Pull request by sergei202**
Quick fix for initial null values.  Issue #3.

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
Good idea. But it might be better to reset the input field in null value?!

**Comment by sergei202** [comment]
Heh, good idea! :sweat_smile:

**Comment by JohannesHoppe** [comment]
Thanks!
v0.0.2 is available on NPM. Please report any errors, if required.

**Comment by JohannesHoppe** [comment]
Hi friends (@nbickel / @sergei202), I would like to extend this project a bit, so that it also supports iso-formatted strings. To do this, I first wanted to understand why the existing code is the way it is.

I have a hard time understanding why we put this if-branch in here. If you set the `valueAsDate` to `null`, I don't get an exception:

```
const value = null;
this._renderer.setElementProperty(this._elementRef.nativeElement, 'valueAsDate', value);  // it works?!
```

There is also no warning or anything like that (in Chrome and Firefox). Has the browser behaviour changed and did an exception occur in the past? Or have I missed something?



see also
https://github.com/JohannesHoppe/angular-date-value-accessor/pull/29/files#diff-b8690fb4a4d2133da0425c46a7c31bf6d51594c6bfc9287a5e8c4e2149fa938dR28-R32

Many thanks for your help! 👍

**Pull request merged**
