### PR TITLE
Add support for timezone / local dates

### PR DESCRIPTION
**Pull request by spierala**

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
This code looks great! 👍 

calling @fmalcher & @d-koppenhagen for a review.

**Comment by d-koppenhagen** [comment]
In general the implementation itself LGTM but as far as I can see, only the part of `@HostListener('input') ...` and the method `writeValue` are slightly different from that ones defined in `DateValueAccessor`.
I think to reduce duplicated code, the repeating parts should be moved into an abstract class / directive and than the `DateValueAccessor` and `LocalDateValueAccessor` directives should extend from it.

**Comment by JohannesHoppe** [comment]
Good point, but without an abstraction people can easily extract the code for their project, if they want. Chances are high, that nobody will use both implementations at the same time.

**Comment by JohannesHoppe** [comment]
But yes, duplicated code is evil, too... 🤔

**Comment by fmalcher** [comment]
LGTM, too. I'd prefer duplication over abstraction here. Refactoring should be possible later if necessary.
Thanks for your amazing work @spierala !

**Comment by JohannesHoppe** [comment]
Screen Shot 2020-12-02 at 10 14 53

FYI, there were two peerDependencies stuck at Angular 10. When installing the new package there should be no warning message anymore.

**Comment by spierala** [comment]
Thanks for the good and fast review! 
It was a pleasure to contribute.

**Pull request merged**
